### ISSUE TITLE
Dostop do baze,.gitignore, Binder

### ISSUE THREAD

**Issue by jaanos** [MatevzKopac/Eksoticni_resort_OPB_2021#1]
Vidim, da imate v `auth_public.py` geslo za bazo, ki je tako za vekomaj objavljeno na internetu. @majbc1999, svetujem, da ga zamenjaš, podatke za povezavo na bazo pa imejte (vsak svoje) v datoteki `auth.py`, ki naj bo navedena v `.gitignore`. V `uvozi_podatke.py` potem podatke za prijavo kličite iz modula `auth`, medtem ko naj bodo v `auth_public.py` podatki za prijavo kot uporabnik `javnost`. Da bo aplikacija potem delovala, poskrbite še, da bo imel pravico uporabe števcev:
```sql
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO javnost;
``` 

Datoteko `.gitignore` imate trenutno za projekt v R-ju, tako da se vam je na git izmuznila mapa `__pycache__`, ki pa tja ne sodi, saj gre za generirane datoteke. Svetujem, da uporabite kar [`.gitignore`](https://github.com/jaanos/OPB-bottle/blob/master/.gitignore) z vzorčnega repozitorija - ta vsebuje tudi vnos za `auth.py`, po potrebi pa si jo lahko seveda tudi prilagodite. Mapo `__pycache__` potem kar pobrišite z repozitorija - po ponovnem zagonu aplikacije se bo sicer spet ustvarila, a je git ne bo ponujal za vključitev v commit. 

Kar se tiče delovanja v Binderju, si poglejte ZaloznikV/OPB-Turisticna_agencija#3. Če povzamem, vse poti v predlogah in pri preusmeritvah bo potrebno podati s funkcijo `url`, ki ji podaste ime ustrezne funkcije in njene morebitne parametre (ti morajo biti podani z imenom).

**Comment by majbc1999** [comment]
Smo popravili praktično vse, kar ste napisali. Binder sedaj našo stran zgenerira in tudi v splošnem dela. Imamo le še nekaj težav, ki jih ne znamo popraviti:
- Binder ne naloži slike ("logotipa" našega resorta)
- napake v rdečem okvirčku (sporočila) ne izginevajo in iskalna vrstica ne dela (težave se z obema stvarema pojavijo samo v Binderju)
- ko ima gost dve rezervaciji v dveh različnih sobah _a_ in _b_ (naprekrivajoča časovna termina) in naroči hrano za termin, ko je v sobi _a_, v tabeli naročil potem izpiše naročilo tako na sobo _a_, kot na sobo _b_. Napaka se pojavi pri joinanju tabele _nastanitve_ na tabelo _hrana_.  Joina nam namreč vse sobe (ki jih je gost kadarkoli obiskal) na obrok. Želeli pa bi, da joina samo tisto nastanitev (sobo), ki ima datum enak datumu obroka.

        SELECT DISTINCT hrana.id, hrana.gost_id, gost.ime, gost.priimek, nastanitve.soba_id, hrana.datum, tip_obroka FROM hrana 
        INNER JOIN gost ON hrana.gost_id = gost.emso 
        INNER JOIN nastanitve ON (hrana.gost_id = nastanitve.gost_id AND hrana.datum = nastanitve.datum)
        WHERE (pripravljena = 0)
        ORDER BY hrana.datum ASC

**Comment by majbc1999** [comment]
Sedaj vse dela, če zaženemo lokalno, v Binderju pa imamo dve manjši (neključni) težavi:

- Binder ne naloži slike ("logotipa" našega resorta)

- napake v rdečem okvirčku (sporočila) ne izginevajo in iskalna vrstica ne dela (lokalno vse dela, samo Binder nagaja)

**Comment by jaanos** [comment]
V redu, sem dodal povezavo na repozitorij za zagovore. Če se še niste, se lahko tako z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Kar se tiče Binderja, bo potrebno poskrbeti še za poti do statičnih datotek, npr. pri
https://github.com/MatevzKopac/Eksoticni_resort_OPB_2021/blob/d27187cf07ad15aa55850d7460fdd0ec9a93cdd7/views/base.html#L19
bo potrebno pot do datoteke podati kot `{{url('static', filename='logo.png')}}` in podobno tudi drugod. To bo rešilo tudi težavo z iskanjem, ki ne deluje zaradi nenaloženega Javascripta. Za sporočila bo potrebno odstraniti parameter `path` tukaj:
https://github.com/MatevzKopac/Eksoticni_resort_OPB_2021/blob/d27187cf07ad15aa55850d7460fdd0ec9a93cdd7/eksoticni_resort.py#L56
(morda bo ga pa treba povsod podati - glejte tudi https://github.com/AnjaTrobec/OPB-e-knjiznica/issues/1#issuecomment-883754667 in sledečo diskusijo).

**Comment by majbc1999** [comment]
Smo popravili še javascript in logotip. Prosimo za posodobitev povezave.

**Comment by jaanos** [comment]
V redu, sem posodobil.
